---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT'] %>
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_zero
  roles_path: ../../roles
  data_bags_path: ../../data_bags
  attributes:
    openstack:
      developer_mode: true
      release: icehouse
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
      allow_remote_root: true
      root_network_acl: "%"
    yum:
      epel:
        baseurl: "http://epel.osuosl.org/6/$basearch"
        enable: true
        gpgkey: "http://epel.osuosl.org/RPM-GPG-KEY-EPEL-6"
    authorization:
      sudo:
        users:
          - vagrant
          - centos
          - ubuntu
          - fedora
    omnibus_updater:
      disabled: true

platforms:
- name: centos-6.5
  driver_plugin: openstack
  driver_config:
    username: centos
    image_ref: "CentOS 6.5"
    attributes:
      mysql:
        version: 5.1
- name: ubuntu-12.04
  driver_plugin: openstack
  driver_config:
    username: ubuntu
    image_ref: "Ubuntu 12.04"
- name: fedora-20
  driver_plugin: openstack
  driver_config:
    username: fedora
    image_ref: "Fedora 20"

suites:
  - name: controller
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::controller]
  - name: controller_managed
    run_list:
      - role[base_managed]
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::controller]
  - name: compute
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::compute]
      - role[openstack_compute]
  - name: compute_managed
    run_list:
      - role[base_managed]
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::compute]
      - role[openstack_compute]
