---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_zero
  roles_path: ../../roles
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: test/integration/default/encrypted_data_bag_secret
  attributes:
    osl-openstack:
      database_suffix: x86
      databag_prefix: x86
      vnc_bind_interface:
        controller: eth0
        compute: eth0
    openstack:
      release: icehouse
      secret:
        key_path: /tmp/kitchen/encrypted_data_bag_secret
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
      allow_remote_root: true
      root_network_acl:
        - "%"
    yum:
      epel:
        baseurl: "http://epel.osuosl.org/6/$basearch"
        enable: true
        gpgkey: "http://epel.osuosl.org/RPM-GPG-KEY-EPEL-6"
    authorization:
      sudo:
        users:
          - vagrant
          - centos
          - ubuntu
          - fedora
    omnibus_updater:
      disabled: true

platforms:
- name: centos-6.6
  driver_plugin: openstack
  driver_config:
    username: centos
    image_ref: "CentOS 6.6"
    attributes:
      mysql:
        version: 5.1
- name: fedora-20
  driver_plugin: openstack
  driver_config:
    username: fedora
    image_ref: "Fedora 20"

suites:
  - name: controller
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
    excludes:
      - fedora-20
  - name: controller_managed
    run_list:
      - role[base_managed]
      - role[openstack_ops_database]
      - role[openstack_controller]
    excludes:
      - fedora-20
  - name: compute
    run_list:
      - recipe[osl-openstack::compute]
      - role[openstack_compute]
  - name: compute_managed
    run_list:
      - role[base_managed]
      - recipe[osl-openstack::compute]
      - role[openstack_compute]
  - name: cinder
    run_list:
      - role[openstack_base]
      - role[openstack_ops_database]
      - recipe[openstack-ops-messaging::server]
      - recipe[openstack-identity::server]
      - recipe[openstack-identity::registration]
      - recipe[osl-openstack::cinder]
    attributes:
      osl-openstack:
        cinder:
          iscsi_role: "openstack_base"
          iscsi_ips:
            - 127.0.2.1
            - 127.0.3.1
      openstack:
        block-storage:
          volume:
            create_volume_group: true
  - name: novnc
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::novnc]
    excludes:
      - fedora-20
