---
verifier:
  name: inspec
driver:
  name: openstack
  flavor_ref: 'm1.large'
  user_data: userdata.txt
provisioner:
  name: chef_zero
  roles_path: test/integration/roles
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  attributes:
    base:
      packages: []
    osl-openstack:
      ceph: true
      database_suffix: x86
      databag_prefix: x86
      endpoint_hostname: controller.example.com
      db_hostname: controller.example.com
      bind_service: 127.0.0.1
      vxlan_interface:
        controller:
          default: lo
      nova_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYOuLkP1F/Sm/dCJAA7kme+ObO4J8x2HrZU40W8QqW4yFqRPKnW5HYLeUpRzIFzWen/LIn6R6lxTfSAnnD8qEEuKbFjH5WRqJYCJeAyaTBTRyU1FHlcTR/EQ/HVZ38TQwCztZgboFb5zmWqYc3/BYBHGA6XeYN5jRcHvZbyaGL+YA1/KPIjpbQfqIPXdHfodoSNX4qQQccYBq2c/rq3Puh7Q9oVph6a2lq0wWsqYyq0vTGHPKFYShVpwDl2Z3c8eB3P7yFRzOR2VNuezJlOgoHz6D/mBObLj1n+yi07bcGbpwAH/rLEyiy4gVdru2qQAcbDL9Yibk96lovim/IH4dV nova-migration
      physical_interface_mappings:
        -
         name: public
         controller:
          default: eth1
         compute:
          default: eth1
    openstack:
      secret:
        key_path: "/tmp/kitchen/encrypted_data_bag_secret"
    ceph:
      fsid-secret: 'ae3f1d03-bacd-4a90-b869-1a4fabb107f2'
      keyring:
        mon: '/etc/ceph/$cluster.mon.keyring'
    mariadb:
      server_root_password: "rootpass"
      forbid_remote_root: false
    yum:
      epel:
        baseurl: http://epel.osuosl.org/7/$basearch
        enabled: true
        gpgkey: http://epel.osuosl.org/RPM-GPG-KEY-EPEL-7
    omnibus_updater:
      disabled: true

suites:
  - name: default
    run_list:
      - recipe[osl-openstack::default]
  - name: mon
    provisioner: chef_solo
    run_list:
      - recipe[osl-openstack::mon]
  - name: mon_controller
    provisioner: chef_solo
    run_list:
      - recipe[osl-openstack::mon]
    attributes:
      osl-openstack:
        node_type: controller
  - name: ops_messaging
    driver_config:
        server_name: "ops-messaging-<%= ENV['USER'] %>"
    run_list:
      - role[openstack_tk]
      - recipe[osl-openstack::ops_messaging]
  - name: identity
    driver_config:
        server_name: "identity-<%= ENV['USER'] %>"
    run_list:
      - role[openstack_tk]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::identity]
      - recipe[openstack_test::cacert]
  - name: image
    driver_config:
        server_name: "image-<%= ENV['USER'] %>"
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - role[ceph_setup]
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::image]
  - name: network
    driver_config:
        server_name: "network-<%= ENV['USER'] %>"
    run_list:
      - recipe[openstack_test]
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::network]
  - name: linuxbridge
    driver_config:
        server_name: "linuxbridge-<%= ENV['USER'] %>"
    run_list:
      - role[openstack_tk]
      - recipe[openstack_test]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::linuxbridge]
  - name: compute_controller
    driver_config:
        server_name: "compute-controller-<%= ENV['USER'] %>"
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::compute_controller]
  - name: compute
    driver_config:
        server_name: "compute-<%= ENV['USER'] %>"
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - role[ceph_setup]
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::compute_controller]
      - recipe[osl-openstack::compute]
  - name: dashboard
    driver_config:
        server_name: "dashboard-<%= ENV['USER'] %>"
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::dashboard]
  - name: block_storage
    driver_config:
        server_name: "block-storage-<%= ENV['USER'] %>"
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - role[ceph_setup]
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::block_storage_controller]
      - recipe[openstack-block-storage::volume_driver_lvm]
      - recipe[osl-openstack::block_storage]
    attributes:
      osl-openstack:
        cinder:
          iscsi_role: openstack_base
          iscsi_ips:
            - 127.0.2.1
            - 127.0.3.1
  - name: block_storage_controller
    driver_config:
        server_name: "block-storage-controller-<%= ENV['USER'] %>"
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::block_storage_controller]
  - name: telemetry
    driver_config:
        server_name: "telemetry-<%= ENV['USER'] %>"
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - role[ceph_setup]
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::telemetry]
  - name: orchestration
    driver_config:
        server_name: "orchestration-<%= ENV['USER'] %>"
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::orchestration]
  - name: controller
    driver_config:
        server_name: "controller-<%= ENV['USER'] %>"
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - role[ceph_setup]
      - role[openstack_tk]
      - recipe[openstack_test]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::controller]
      - recipe[openstack-integration-test::setup]
      - recipe[openstack_test::tempest]
  - name: allinone
    driver_config:
        server_name: "allinone-<%= ENV['USER'] %>"
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - role[ceph_setup]
      - role[openstack_tk]
      - recipe[openstack_test]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::compute]
      - recipe[osl-openstack::block_storage]
      - recipe[openstack_test::tempest]
      - recipe[openstack_test::orchestration]
    attributes:
      osl-openstack:
        cinder:
          iscsi_role: openstack_base
          iscsi_ips:
            - 127.0.2.1
            - 127.0.3.1
      openstack:
        block-storage:
          volume:
            create_volume_group: true
  - name: upgrade
    driver_config:
        server_name: "upgrade-<%= ENV['USER'] %>"
    driver:
      image_ref: "openstack-ocata-aio"
    verifier:
      inspec_tests:
        - path: test/integration/controller/inspec
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - role[ceph_setup]
      - recipe[openstack_test::upgrade_start]
      - role[openstack_tk]
      - recipe[osl-openstack::upgrade]
      - recipe[openstack_test::upgrade]
      - recipe[openstack_test]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::compute]
      - recipe[openstack-block-storage::volume_driver_lvm]
      - recipe[osl-openstack::block_storage]
      - recipe[openstack-integration-test::setup]
      - recipe[openstack_test::tempest]
      - recipe[openstack_test::orchestration]
    attributes:
      osl-openstack:
        node_type: controller
        endpoint_hostname: controller.example.com
        db_hostname: controller.example.com
        cinder:
          iscsi_role: openstack_base
          iscsi_ips:
            - 127.0.2.1
            - 127.0.3.1
      openstack:
        block-storage:
          volume:
            create_volume_group: true
  - name: multi-node
    driver:
      name: terraform
      command_timeout: 3600
    provisioner: terraform
    verifier:
      name: terraform
      groups:
        - name: controller
          controls:
            - controller
          hostnames: controller
        - name: compute
          controls:
            - compute
          hostnames: compute
