---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: ../../roles
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: test/integration/default/encrypted_data_bag_secret

  attributes:
    osl-openstack:
      database_suffix: x86
      databag_prefix: x86
    openstack:
      release: icehouse
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
      allow_remote_root: true
      root_network_acl:
        - "%"
    yum:
      epel:
        baseurl: "http://epel.osuosl.org/6/$basearch"
        enable: true
        gpgkey: "http://epel.osuosl.org/RPM-GPG-KEY-EPEL-6"
    authorization:
      sudo:
        users:
          - vagrant
          - centos
          - ubuntu
          - fedora
    omnibus_updater:
      disabled: true

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5
    attributes:
      mysql:
        version: 5.1
  - name: fedora-20

suites:
  - name: controller
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
    excludes:
      - fedora-20
  - name: controller_managed
    run_list:
      - role[base_managed]
      - role[openstack_ops_database]
      - role[openstack_controller]
    excludes:
      - fedora-20
  - name: compute
    run_list:
      - recipe[osl-openstack::compute]
      - role[openstack_compute]
  - name: compute_managed
    run_list:
      - role[base_managed]
      - recipe[osl-openstack::compute]
      - role[openstack_compute]
  - name: novnc
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::novnc]
    excludes:
      - fedora-20
