---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: ../../roles
  data_bags_path: ../../data_bags
  attributes:
    openstack:
      developer_mode: true
      release: havanah
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
      allow_remote_root: true
      root_network_acl: "%"
      version: 5.1
    yum:
      epel:
        baseurl: "http://epel.osuosl.org/6/$basearch"
        enable: true
        gpgkey: "http://epel.osuosl.org/RPM-GPG-KEY-EPEL-6"
    authorization:
      sudo:
        users:
          - vagrant
          - centos
          - ubuntu
          - fedora
    omnibus_updater:
      disabled: true

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5
  - name: fedora-20

suites:
  - name: controller
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::controller]
  - name: controller_managed
    run_list:
      - role[base_managed]
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::controller]
  - name: compute
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::compute]
      - role[openstack_compute]
  - name: compute_managed
    run_list:
      - role[base_managed]
      - role[openstack_ops_database]
      - role[openstack_controller]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::compute]
      - role[openstack_compute]
