---
driver:
  flavor_ref: 'm1.large'
provisioner:
  name: chef_zero
  roles_path: test/integration/roles
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: test/integration/default/encrypted_data_bag_secret
  attributes:
    osl-openstack:
      database_suffix: x86
      databag_prefix: x86
      vnc_bind_interface:
        controller: eth0
        compute: eth0
    openstack:
      secret:
        key_path: "/tmp/kitchen/encrypted_data_bag_secret"
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
      allow_remote_root: true
      root_network_acl:
        - "%"
    yum:
      epel:
        baseurl: http://epel.osuosl.org/7/$basearch
        enable: true
        gpgkey: http://epel.osuosl.org/RPM-GPG-KEY-EPEL-7
    scl:
      packages:
        - python27
    omnibus_updater:
      disabled: true

suites:
  - name: default
    run_list:
      - recipe[osl-openstack::default]
  - name: allinone
    run_list:
      - role[openstack_tk]
      - recipe[openstack_test]
      - recipe[firewall::mysql]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::compute]
      - recipe[osl-openstack::cinder]
      - recipe[openstack-integration-test::setup]
    attributes:
      osl-openstack:
        endpoint_hostname: localhost
        cinder:
          iscsi_role: openstack_base
          iscsi_ips:
            - 127.0.2.1
            - 127.0.3.1
      openstack:
        block-storage:
          volume:
            create_volume_group: true
  - name: mon
    provisioner: chef_solo
    run_list:
      - recipe[osl-openstack::mon]
  - name: ops_messaging
    run_list:
      - role[openstack_tk]
      - recipe[osl-openstack::ops_messaging]
  - name: identity
    run_list:
      - role[openstack_tk]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::identity]
  - name: image
    run_list:
      - role[openstack_tk]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::identity]
      - recipe[osl-openstack::image]
  - name: network
    run_list:
      - role[openstack_tk]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::identity]
      - recipe[osl-openstack::network]
  - name: controller
    run_list:
      - role[openstack_tk]
      - recipe[firewall::mysql]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::controller]
      - recipe[openstack-integration-test::setup]
  - name: compute
    run_list:
      - role[openstack_tk]
      - recipe[firewall::mysql]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::identity]
      - recipe[openstack-compute::nova-setup]
      - recipe[openstack-compute::identity_registration]
      - recipe[openstack-compute::conductor]
      - recipe[openstack-compute::scheduler]
      - recipe[osl-openstack::compute]
  - name: cinder
    run_list:
      - role[openstack_tk]
      - recipe[firewall::mysql]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::identity]
      - recipe[osl-openstack::cinder]
    attributes:
      osl-openstack:
        cinder:
          iscsi_role: openstack_base
          iscsi_ips:
            - 127.0.2.1
            - 127.0.3.1
      openstack:
        block-storage:
          volume:
            create_volume_group: true
  - name: novnc
    run_list:
      - role[openstack_tk]
      - recipe[firewall::mysql]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::novnc]
