---
driver:
  flavor_ref: 'm1.large'
provisioner:
  name: chef_zero
  roles_path: test/integration/roles
  data_bags_path: test/integration/default/data_bags
  encrypted_data_bag_secret_key_path: test/integration/default/encrypted_data_bag_secret
  attributes:
    osl-openstack:
      database_suffix: x86
      databag_prefix: x86
      endpoint_hostname: controller.example.com
      vnc_bind_interface:
        controller: eth0
        compute: eth0
    openstack:
      secret:
        key_path: "/tmp/kitchen/encrypted_data_bag_secret"
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
      allow_remote_root: true
      root_network_acl:
        - "%"
    yum:
      epel:
        baseurl: http://epel.osuosl.org/7/$basearch
        enable: true
        gpgkey: http://epel.osuosl.org/RPM-GPG-KEY-EPEL-7
    scl:
      packages:
        - python27
    omnibus_updater:
      disabled: true

suites:
  - name: default
    run_list:
      - recipe[osl-openstack::default]
  - name: mon
    provisioner: chef_solo
    run_list:
      - recipe[osl-openstack::mon]
  - name: mon_controller
    provisioner: chef_solo
    run_list:
      - recipe[osl-openstack::mon]
    attributes:
      osl-openstack:
        node_type: controller
  - name: ops_messaging
    run_list:
      - role[openstack_tk]
      - recipe[osl-openstack::ops_messaging]
  - name: identity
    run_list:
      - role[openstack_tk]
      - recipe[osl-openstack::ops_database]
      - recipe[osl-openstack::identity]
      - recipe[openstack_test::cacert]
  - name: image
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[openstack_test::gluster]
      - recipe[osl-openstack::image]
  - name: network
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::network]
  - name: linuxbridge
    run_list:
      - role[openstack_tk]
      - recipe[openstack_test]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::linuxbridge]
    attributes:
      osl-openstack:
        physical_interface_mappings:
          -
           name: public
           controller:
            default: eth1
           compute:
            default: eth1
  - name: compute_controller
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::compute_controller]
  - name: compute
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::compute_controller]
      - recipe[osl-openstack::compute]
  - name: dashboard
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::dashboard]
  - name: block_storage
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::block_storage_controller]
      - recipe[openstack-block-storage::volume_driver_lvm]
      - recipe[osl-openstack::block_storage]
    attributes:
      osl-openstack:
        cinder:
          iscsi_role: openstack_base
          iscsi_ips:
            - 127.0.2.1
            - 127.0.3.1
  - name: block_storage_controller
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::block_storage_controller]
  - name: telemetry
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[osl-openstack::telemetry]
  - name: controller
    run_list:
      - role[openstack_tk]
      - role[openstack_ops_identity]
      - recipe[openstack_test::gluster]
      - recipe[osl-openstack::controller]
      - recipe[openstack-integration-test::setup]
  - name: allinone
    run_list:
      - role[openstack_tk]
      - recipe[openstack_test]
      - role[openstack_ops_identity]
      - recipe[openstack_test::gluster]
      - recipe[osl-openstack::controller]
      - recipe[osl-openstack::compute]
      - recipe[osl-openstack::cinder]
      - recipe[openstack-integration-test::setup]
    attributes:
      osl-openstack:
        endpoint_hostname: localhost
        cinder:
          iscsi_role: openstack_base
          iscsi_ips:
            - 127.0.2.1
            - 127.0.3.1
      openstack:
        block-storage:
          volume:
            create_volume_group: true
