AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - 'metadata.rb'
    - 'cookbooks/**/*'
    - 'test/chef-config/knife.rb'
Metrics/BlockNesting:
  Max: 4
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
Metrics/LineLength:
  Max: 120
Style/IfUnlessModifier:
  MaxLineLength: 120
Style/WhileUntilModifier:
  MaxLineLength: 120
Metrics/BlockLength:
  Enabled: false
