Metrics/BlockNesting:
  Max: 4
AllCops:
  TargetChefVersion: 16.latest
  Exclude:
    - "cookbooks/**/*"
Chef/Modernize/FoodcriticComments:
  Enabled: true
Chef/Style/CopyrightCommentFormat:
  Enabled: true
