#!/bin/bash
export PATH="/opt/cinc/embedded/bin:$PATH"
source /root/openrc
source /usr/local/etc/os_cluster
PROM_FILE=/var/lib/node_exporter/openstack.prom
mkdir -p /var/lib/node_exporter/
/usr/local/libexec/openstack-prometheus.rb > ${PROM_FILE}.$$
mv ${PROM_FILE}.$$ ${PROM_FILE}
