prometheus_endpoint = input('prometheus_endpoint')

control 'telemetry-controller' do
  %w(
    openstack-ceilometer-central
    openstack-ceilometer-common
    openstack-ceilometer-notification
  ).each do |p|
    describe package p do
      it { should be_installed }
    end
  end

  %w(
    openstack-ceilometer-central
    openstack-ceilometer-notification
  ).each do |s|
    describe service s do
      it { should be_enabled }
      it { should be_running }
    end
  end

  describe file '/etc/ceilometer/pipeline.yaml' do
    its('content') { should match %r{publishers:\n\s+- prometheus://#{prometheus_endpoint}:9091/metrics/job/ceilometer} }
  end

  describe file '/etc/ceilometer/polling.yaml' do
    its('content') { should match /This file is automatically generated by Chef/ }
    its('content') { should match /interval: 60/ }
  end

  describe ini('/etc/ceilometer/ceilometer.conf') do
    its('DEFAULT.transport_url') { should cmp 'rabbit://openstack:openstack@controller.testing.osuosl.org:5672' }
    its('cache.memcache_servers') { should cmp 'controller.testing.osuosl.org:11211' }
    its('service_credentials.auth_url') { should cmp 'https://controller.testing.osuosl.org:5000/v3' }
    its('service_credentials.password') { should cmp 'ceilometer' }
  end

  describe http('http://localhost:9091/metrics') do
    its('body') { should match /^image_size{instance="",job="ceilometer",project_id="/ }
  end
end
